// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';
import TitleAndText from './TitleAndText';

export {
	ContactForm,
	Image,
	Quote,
	Text,
	TitleAndText,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
	title_and_text: TitleAndText,
};
